### PR TITLE
GitHub Action Improvements + More

### LINKED ISSUE #8: Create GitHub Actions
Having GitHub Actions Automatically Run when a Pull Request is created is a good way to make sure that we aren't going to break anything by merging. The following are examples of some that would be useful.

- [x] Unit/Integration Tests
- [x] Doxgen Builder and then host on GitHub Pages
- [x] CodeQL Security Checks
- [x] Image Builders and Publishers
- [x] Executable Builder and Releaser

### LINKED ISSUE #13: Autodocumentation with Doxygen and Gihub pages.
# Auto-documentation of dev branch

Configure doxygen for Autonomy_Software and use github actions to generate and push documentation to gh-pages branch.

### PR DESCRIPTION
**Pull request by Byrdman32**
- [x] Fix typos that were present in #14 
- [x] Fix permission levels required for package deployment
- [x] Transfer Ubuntu Image to GitHub Container Registry
- [x] Transfer JetPack Image to GitHub Container Registry
- [x] Add License to project
- [x] Add deployment of documentation
- [x] Add codeql to project
- [x] Increment Version Numbers

### CODE REVIEW

**Review by ClayJay3 — DISMISSED** [review]

**Review by ClayJay3 — DISMISSED** [review]

**Review by ClayJay3 — DISMISSED** [review]

**Comment by Byrdman32** [comment]
Am I correct that when we switch the default branch to development you will be changing the target branch back to development?

**Comment by ClayJay3** [comment]
Yeah, I just wanted to test something.

**Comment by Byrdman32** [comment]
Also, I got rid of the two release branches since I realized it was going to make things more complicated having the development branch and then making GitHub releases will be much easier. And we will have tags that can be checked out if someone wants a specific version.

**Comment by Byrdman32** [comment]
image

So, we need to figure out how to make the JetPack Image take less time to build.

**Comment by ClayJay3** [comment]
Damn. I can work on that, I've already started on it since I got cuda support for OpenCV working in the Ubuntu image. I'v also working on setting up codeql, unless you want finish that since you've been doing the GitHub actions. I don't know how beneficial it will be, but it might end up being helpful later on.

**Comment by Byrdman32** [comment]
I can look into `codeql`. I have heard about it but haven't done much with it before. If you want to tackle getting the JetPack image to build faster that would be great. I think part of the issue was that we had to use the emulated version of arm64 since you can't use arm64 as your target in GitHub currently. I have looked at potentially creating a self hosted action but don't know if it would go much faster.

**Review by ClayJay3 — APPROVED** [review]

**Pull request merged**
