### PR TITLE
Add ffmpeg amd64

### PR DESCRIPTION
**Pull request by Byrdman32**

### CODE REVIEW

**Review by ClayJay3 — APPROVED** [review]

**Comment by ClayJay3** [comment]
Can we close this PR?

**Comment by Byrdman32** [comment]
Maybe, let me check tomorrow or Saturday

**Comment by Byrdman32** [comment]
After closer review, I'm good at closing this PR but I'm going to keep the branch open until I can copy some stuff over to the camera server repository

**Comment by Byrdman32** [comment]
Deleting the branch as all vital info has already been copied.

**Pull request closed without merging**
